{% set name = "taskflow" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taskflow/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 66b891f706ba99a5ca5ed239d520ad6943ebe94728d1c89e07a939615a6488ef

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('cxx') }}

test:
  commands:
    - test -d ${PREFIX}/include/taskflow  # [unix]
    - test -f ${PREFIX}/include/taskflow/taskflow.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\taskflow\taskflow.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/taskflow/taskflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parallel and Heterogeneous Task Programming in Modern C++
  doc_url: https://taskflow.github.io/taskflow/index.html
  dev_url: https://github.com/taskflow/taskflow

extra:
  recipe-maintainers:
    - davidbrochart
